name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get local.properties from secrets
      env:           
        NEWSAPIKEY: ${{ secrets.NEWSAPIKEY }}
      run: |
        sed "s|NEWSAPIKEY|$NEWSAPIKEY|g;" local.defaults.properties > local.properties
    - name: Build with Gradle
      run: ./gradlew build
